### PR TITLE
Updated Readme, Fixed FT detection, Added better support

### PR DESCRIPTION
**Pull request by niftylettuce**
Please accept this PR 👍

### CODE REVIEW

**Comment by lepture** [comment]
It has conflicts

**Comment by niftylettuce** [comment]
@lepture should be OK now - not sure what was the reason why it said that

**Comment by lepture** [comment]
@niftylettuce cloud you cleanup the PR? It two lines of changes with 10 commits. Could you squash them into one commit?

**Comment by niftylettuce** [comment]
@lepture done

**Pull request merged**
